name: field-service-minisoccerbook # change this to your app name
services:
  # Postgres Service
  postgres:
    image: postgres:latest
    container_name: postgres1
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - user-service-minisoccerbook-network

  # API Field Service
  user-service:
    build: .
    image: field-service:1.0.0
    container_name: field-service
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - SIGNATURE_KEY=${SIGNATURE_KEY}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAX_OPEN_CONNECTIONS=${DB_MAX_OPEN_CONNECTIONS}
      - DB_MAX_LIFETIME_CONNECTION=${DB_MAX_LIFETIME_CONNECTION}
      - DB_MAX_IDLE_CONNECTIONS=${DB_MAX_IDLE_CONNECTIONS}
      - DB_MAX_IDLE_TIME=${DB_MAX_IDLE_TIME}
      - RATE_LIMITER_MAX_REQUEST=${RATE_LIMITER_MAX_REQUEST}
      - RATE_LIMITER_TIME_SECOND=${RATE_LIMITER_TIME_SECOND}
      - INTERNAL_SERVICE_USER_HOST=${INTERNAL_SERVICE_USER_HOST}
      - INTERNAL_SERVICE_USER_SIGNATURE_KEY=${INTERNAL_SERVICE_USER_SIGNATURE_KEY}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET=${MINIO_SECRET}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,PATCH
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,x-service-name,x-request-at,x-api-key
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_EXPOSE_HEADERS=Content-Length,Content-Type
    networks:
      - user-service-minisoccerbook-network

volumes:
  postgresql_data:

networks:
  user-service-minisoccerbook-network:
    driver: bridge
